# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
orbs:
   aws-s3: circleci/aws-s3@3.0

jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.13

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/ui-driver-upcloud

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install
      - run: npm run build

      - persist_to_workspace:
          root: .
          paths: dist

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  deploy:
    docker:
      - image: circleci/node:10.13
    steps:
      - attach_workspace:
         # Must be absolute path or relative path from working_directory
         at: workspace
      - run:
          name: Get deploy dir
          command: |
            echo 'export DEPLOY_DIR=$( if [[ "$CIRCLE_TAG" =~ "^v.*" ]]; then echo "$CIRCLE_TAG"; else echo "${CIRCLE_SHA1:0:7}"; fi )' >> $BASH_ENV

      - aws-s3/sync:
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-region: AWS_REGION
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          from: workspace/dist
          to: "s3://upcloud-rancher-driver/ui/${DEPLOY_DIR}"

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build

  tagged-build-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/

